# Autogenerated wrapper script for blis32_jll for x86_64-unknown-freebsd
export blis32

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("blis32")
JLLWrappers.@declare_library_product(blis32, "libblis32.so")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        blis32,
        "lib/libblis32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
